print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = float(input("What percentage tip would you like to give? 10 12 15 "))
people = int(input("How many people to split the bill? "))
bill_individual = round(float((bill + bill * (tip / 100))/people),2)
print(f"The bill divided for each individual is ${bill_individual}")
